### PR TITLE
fix #60

### LINKED ISSUE #60: Feature request: brazillian portuguese translation

### PR DESCRIPTION
**Pull request by Plasmmer**

### CODE REVIEW

**Comment by Plasmmer** [comment]
@HelloZeroNet

**Comment by HelloZeroNet** [comment]
Thanks!

**Comment by Plasmmer** [comment]
@HelloZeroNet 
I can't see the portuguese language working.

**Comment by HelloZeroNet** [comment]
Just added pt-br to zerohello language options + fixed the encoding of the pt-br.json

**Comment by Plasmmer** [comment]
https://github.com/HelloZeroNet/ZeroHello/pull/46
@HelloZeroNet Added pt-br.json to HelloZeroNet.

**Pull request merged**
